name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'chris-peterson/pwsh-artifactory'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}

    environment:
      name: PowerShell Gallery
      url: https://www.powershellgallery.com/packages/ArtifactoryCli
